services:
  comfyui-worker:
    image: yankeehotelfoxtrot51/worker-comfyui:custom
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
    develop:
      watch:
        - action: sync+restart
          path: ./handler.py
          target: /handler.py
